---
title: "Untitled"
output: pdf_document
---

```{r}
a <- read.table("http://www.stat.ucla.edu/~nchristo/statistics100c/restaurant.txt",header = T)
y <- a$cost
x1 <- a$food
x2 <- a$decor
x3 <- a$ser
ones <- rep(1, nrow(a))

X <- as.matrix(cbind(ones, x1, x2, x3))

XtraX <- solve(t(X) %*% X)
beta_hat <- XtraX %*% t(X) %*% y
se2 <- (t(y) %*% y - t(beta_hat) %*% t(X) %*% y) / (nrow(a) - 3 - 1)
```


```{r}
v <- c(0,1,0,0,0,0,1,0,0,0,0,1)
C <- matrix(v, nrow = 3, ncol=4, byrow = T)
gamma <- as.matrix(rep(0,3))
F <- (t(C %*% beta_hat) %*% solve(C %*% XtraX %*% t(C)) %*% (C %*% beta_hat)) / (3*se2)
F > qf(p = 0.975, df1 = nrow(C), df2 = nrow(a)-3-1)
```

```{r}
v <- c(0,1,0,0,0,0,0,1)
C <- matrix(v, nrow = 2, ncol=4, byrow = T)
gamma <- as.matrix(rep(0,2))
F <- (t(C %*% beta_hat) %*% solve(C %*% XtraX %*% t(C)) %*% (C %*% beta_hat)) / (nrow(C)*se2)
F > qf(p = 0.975, df1 = nrow(C), df2 = nrow(a)-3-1)
```

```{r}
c_1 <- c(1, 5, 20, 3)
c_2 <- c(1,1,1,1)
c_3 <- c(1,-3,-1,1)

C <- matrix(cbind(c_1,c_2,c_3),nrow = 3, ncol = 4,byrow = T)

gamma <- matrix(cbind(0,-25,-40))

beta_c <- beta_hat + XtraX %*% t(C) %*% solve(C %*% XtraX %*%  t(C)) %*% (gamma-C %*% beta_hat)  
```
